name: Say hello


on:
  push:
    branches:
      - main
jobs:
  hello_word:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello World to me "
      - name: get me the date
        run: date
      - run: ls -l
      