name: Deployment Pipeline
on:
  push:
    branches:
      - main
jobs:
  cancel_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
      - name: run build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: run eslint
        run: npm run eslint
     
  test:
    needs: [build,linter]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      
      - name: run test
        run: npm run test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: run eslint
        run: npm run eslint
      - name: run test
        run: npm run test
      - name: Build
        run: npm run build
      - name: run test e2e
        run: npm run test:e2e
      

